--SET SERVEROUTPUT ON
SET DEFINE OFF

-- ================================================================
-- STEP 1: DROP EXISTING TABLES
-- ================================================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SOFTWARE_TECHNOLOGY CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MAINTENANCE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BUG CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE VERSION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LICENSE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SOFTWARE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PROJECT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DEPARTMENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "USER" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TECHNOLOGY CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- ================================================================
-- STEP 2: CREATE TABLES
-- ================================================================

-- TABLE 1: USER
-- "USER" is quoted because USER is a special Oracle keyword/function.
CREATE TABLE "USER" (
    User_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) NOT NULL UNIQUE,
    Password VARCHAR2(255) NOT NULL
);

-- TABLE 2: DEPARTMENT
CREATE TABLE DEPARTMENT (
    Department_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Department_Name VARCHAR2(100) NOT NULL,
    Description CLOB,
    Location VARCHAR2(100),
    Contact_Email VARCHAR2(100)
);

-- TABLE 3: PROJECT
CREATE TABLE PROJECT (
    Project_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Project_Name VARCHAR2(150) NOT NULL,
    Description CLOB,
    Start_Date DATE,
    End_Date DATE,
    Project_Status VARCHAR2(50) DEFAULT 'Planning',
    Department_ID NUMBER NOT NULL,
    CONSTRAINT FK_PROJECT_DEPARTMENT
        FOREIGN KEY (Department_ID)
        REFERENCES DEPARTMENT(Department_ID)
        ON DELETE CASCADE
);

-- TABLE 4: DEVELOPER
CREATE TABLE DEVELOPER (
    Developer_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Developer_Name VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) NOT NULL,
    Department_ID NUMBER NOT NULL,
    CONSTRAINT FK_DEVELOPER_DEPARTMENT
        FOREIGN KEY (Department_ID)
        REFERENCES DEPARTMENT(Department_ID)
        ON DELETE CASCADE
);

-- TABLE 5: SOFTWARE
CREATE TABLE SOFTWARE (
    Software_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Software_Name VARCHAR2(150) NOT NULL,
    Description CLOB,
    Status VARCHAR2(50) DEFAULT 'Active',
    Project_ID NUMBER NOT NULL,
    CONSTRAINT FK_SOFTWARE_PROJECT
        FOREIGN KEY (Project_ID)
        REFERENCES PROJECT(Project_ID)
        ON DELETE CASCADE
);

-- TABLE 6: VERSION
CREATE TABLE VERSION (
    Version_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Software_ID NUMBER NOT NULL,
    Version_Number VARCHAR2(50) NOT NULL,
    Release_Date DATE NOT NULL,
    CONSTRAINT FK_VERSION_SOFTWARE
        FOREIGN KEY (Software_ID)
        REFERENCES SOFTWARE(Software_ID)
        ON DELETE CASCADE
);

-- TABLE 7: BUG
CREATE TABLE BUG (
    Bug_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Software_ID NUMBER NOT NULL,
    Description CLOB NOT NULL,
    Severity VARCHAR2(30) DEFAULT 'Medium' NOT NULL,
    Status VARCHAR2(30) DEFAULT 'Open' NOT NULL,
    Reported_Date DATE NOT NULL,
    CONSTRAINT FK_BUG_SOFTWARE
        FOREIGN KEY (Software_ID)
        REFERENCES SOFTWARE(Software_ID)
        ON DELETE CASCADE
);

-- TABLE 8: MAINTENANCE
CREATE TABLE MAINTENANCE (
    Maintenance_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Bug_ID NUMBER NOT NULL,
    Maintenance_Date DATE NOT NULL,
    Description CLOB NOT NULL,
    Performed_By NUMBER NOT NULL,
    Status VARCHAR2(30) DEFAULT 'In Progress' NOT NULL,
    CONSTRAINT FK_MAINTENANCE_BUG
        FOREIGN KEY (Bug_ID)
        REFERENCES BUG(Bug_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_MAINTENANCE_DEVELOPER
        FOREIGN KEY (Performed_By)
        REFERENCES DEVELOPER(Developer_ID)
        ON DELETE CASCADE
);

-- TABLE 9: LICENSE
CREATE TABLE LICENSE (
    License_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Software_ID NUMBER NOT NULL,
    License_Type VARCHAR2(50) NOT NULL,
    Start_Date DATE NOT NULL,
    Expiry_Date DATE NOT NULL,
    License_Status VARCHAR2(30) DEFAULT 'Active' NOT NULL,
    CONSTRAINT FK_LICENSE_SOFTWARE
        FOREIGN KEY (Software_ID)
        REFERENCES SOFTWARE(Software_ID)
        ON DELETE CASCADE
);

-- TABLE 10: TECHNOLOGY
CREATE TABLE TECHNOLOGY (
    Technology_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Technology_Name VARCHAR2(100) NOT NULL,
    Technology_Type VARCHAR2(50) NOT NULL,
    Version VARCHAR2(50),
    Description CLOB
);

-- TABLE 11: SOFTWARE_TECHNOLOGY
-- Junction table for SOFTWARE <-> TECHNOLOGY many-to-many relationship
CREATE TABLE SOFTWARE_TECHNOLOGY (
    Software_ID NUMBER NOT NULL,
    Technology_ID NUMBER NOT NULL,
    CONSTRAINT PK_SOFTWARE_TECHNOLOGY
        PRIMARY KEY (Software_ID, Technology_ID),
    CONSTRAINT FK_ST_SOFTWARE
        FOREIGN KEY (Software_ID)
        REFERENCES SOFTWARE(Software_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_ST_TECHNOLOGY
        FOREIGN KEY (Technology_ID)
        REFERENCES TECHNOLOGY(Technology_ID)
        ON DELETE CASCADE
);

-- ================================================================
-- STEP 3: SAMPLE DATA
-- ================================================================

-- 1. SAMPLE USERS
INSERT INTO "USER" (Name, Email, Password) VALUES
('System Administrator',
 'admin@sms.com',
 'scrypt:32768:8:1$jEYU4vilnsMMruON$a8696cbd3566358aa712ad7ec8f6de05dbeff5011208ca5470f645a75466acb928d29720b64e2c0708347957b3ab4a7d173178c4e74b4912342e7b3603bb7386');

INSERT INTO "USER" (Name, Email, Password) VALUES
('Prof. Rajesh Sharma',
 'rajesh.sharma@sms.com',
 'scrypt:32768:8:1$jEYU4vilnsMMruON$a8696cbd3566358aa712ad7ec8f6de05dbeff5011208ca5470f645a75466acb928d29720b64e2c0708347957b3ab4a7d173178c4e74b4912342e7b3603bb7386');

INSERT INTO "USER" (Name, Email, Password) VALUES
('Ananya Gupta',
 'ananya.gupta@sms.com',
 'scrypt:32768:8:1$jEYU4vilnsMMruON$a8696cbd3566358aa712ad7ec8f6de05dbeff5011208ca5470f645a75466acb928d29720b64e2c0708347957b3ab4a7d173178c4e74b4912342e7b3603bb7386');

-- 2. SAMPLE DEPARTMENTS
INSERT INTO DEPARTMENT
(Department_Name, Description, Location, Contact_Email)
VALUES
('Computer Science & Engineering',
 'Core computing, systems engineering, and software architectures.',
 'Building 3, Floor 2',
 'cse.dept@college.edu');

INSERT INTO DEPARTMENT
(Department_Name, Description, Location, Contact_Email)
VALUES
('Information Technology',
 'Enterprise information systems, networking, and cloud services.',
 'Building 2, Floor 1',
 'it.dept@college.edu');

INSERT INTO DEPARTMENT
(Department_Name, Description, Location, Contact_Email)
VALUES
('Data Science & AI',
 'Machine learning systems, analytics platforms, and predictive modeling.',
 'Academic Block A, Floor 4',
 'ai.dept@college.edu');

INSERT INTO DEPARTMENT
(Department_Name, Description, Location, Contact_Email)
VALUES
('Software Quality Assurance',
 'Testing, code auditing, security review, and reliability engineering.',
 'Innovation Center, Room 102',
 'qa.dept@college.edu');

-- 3. SAMPLE PROJECTS
INSERT INTO PROJECT
(Project_Name, Description, Start_Date, End_Date, Project_Status, Department_ID)
VALUES
('Campus ERP Platform',
 'Integrated enterprise portal for attendance, grading, and course registration.',
 DATE '2025-01-10', DATE '2025-12-20', 'In Progress', 1);

INSERT INTO PROJECT
(Project_Name, Description, Start_Date, End_Date, Project_Status, Department_ID)
VALUES
('Healthcare Management Suite',
 'Clinical workflow system for hospital records and outpatient scheduling.',
 DATE '2024-06-01', DATE '2025-05-30', 'Completed', 2);

INSERT INTO PROJECT
(Project_Name, Description, Start_Date, End_Date, Project_Status, Department_ID)
VALUES
('Predictive Analytics Engine',
 'AI-powered student performance predictor and recommendation engine.',
 DATE '2025-03-01', DATE '2026-02-28', 'In Progress', 3);

INSERT INTO PROJECT
(Project_Name, Description, Start_Date, End_Date, Project_Status, Department_ID)
VALUES
('Secure Exam Portal',
 'Proctored online examination software with real-time anomaly detection.',
 DATE '2025-02-15', DATE '2025-11-30', 'Planning', 4);

INSERT INTO PROJECT
(Project_Name, Description, Start_Date, End_Date, Project_Status, Department_ID)
VALUES
('Library Automation System',
 'RFID enabled book tracking, cataloging, and digital fine collection.',
 DATE '2024-01-15', DATE '2024-09-30', 'Completed', 1);

-- 4. SAMPLE DEVELOPERS
INSERT INTO DEVELOPER
(Developer_Name, Email, Department_ID)
VALUES ('Rahul Verma', 'rahul.verma@college.edu', 1);

INSERT INTO DEVELOPER
(Developer_Name, Email, Department_ID)
VALUES ('Priya Nair', 'priya.nair@college.edu', 1);

INSERT INTO DEVELOPER
(Developer_Name, Email, Department_ID)
VALUES ('Arjun Mehta', 'arjun.mehta@college.edu', 2);

INSERT INTO DEVELOPER
(Developer_Name, Email, Department_ID)
VALUES ('Sneha Roy', 'sneha.roy@college.edu', 2);

INSERT INTO DEVELOPER
(Developer_Name, Email, Department_ID)
VALUES ('Vikram Patel', 'vikram.patel@college.edu', 3);

INSERT INTO DEVELOPER
(Developer_Name, Email, Department_ID)
VALUES ('Neha Kulkarni', 'neha.kulkarni@college.edu', 4);

INSERT INTO DEVELOPER
(Developer_Name, Email, Department_ID)
VALUES ('Aditya Rao', 'aditya.rao@college.edu', 1);

-- 5. SAMPLE SOFTWARE
INSERT INTO SOFTWARE
(Software_Name, Description, Status, Project_ID)
VALUES
('Student Attendance Tracker',
 'Biometric and RFID attendance tracking web application.',
 'Active', 1);

INSERT INTO SOFTWARE
(Software_Name, Description, Status, Project_ID)
VALUES
('Fee Payment Gateway Service',
 'Microservice handling PCI-compliant online tuition fee transactions.',
 'Active', 1);

INSERT INTO SOFTWARE
(Software_Name, Description, Status, Project_ID)
VALUES
('Electronic Medical Record App',
 'HIPAA compliant patient chart and diagnostic summary management.',
 'Active', 2);

INSERT INTO SOFTWARE
(Software_Name, Description, Status, Project_ID)
VALUES
('ML Model Serving API',
 'FastAPI microservice exposing trained student retention models.',
 'Active', 3);

INSERT INTO SOFTWARE
(Software_Name, Description, Status, Project_ID)
VALUES
('Exam Lockdown Browser Utility',
 'Desktop agent preventing browser tab switching during exams.',
 'Testing', 4);

INSERT INTO SOFTWARE
(Software_Name, Description, Status, Project_ID)
VALUES
('OPAC Book Search Portal',
 'Online Public Access Catalog interface for library visitors.',
 'Archived', 5);

-- 6. SAMPLE VERSIONS
INSERT INTO VERSION (Software_ID, Version_Number, Release_Date)
VALUES (1, 'v1.0.0', DATE '2025-02-01');

INSERT INTO VERSION (Software_ID, Version_Number, Release_Date)
VALUES (1, 'v1.1.0', DATE '2025-04-15');

INSERT INTO VERSION (Software_ID, Version_Number, Release_Date)
VALUES (1, 'v2.0.0', DATE '2025-08-10');

INSERT INTO VERSION (Software_ID, Version_Number, Release_Date)
VALUES (2, 'v1.0.0-rc', DATE '2025-03-01');

INSERT INTO VERSION (Software_ID, Version_Number, Release_Date)
VALUES (2, 'v1.0.1', DATE '2025-05-12');

INSERT INTO VERSION (Software_ID, Version_Number, Release_Date)
VALUES (3, 'v3.2.0', DATE '2024-11-20');

INSERT INTO VERSION (Software_ID, Version_Number, Release_Date)
VALUES (3, 'v3.3.1', DATE '2025-01-15');

INSERT INTO VERSION (Software_ID, Version_Number, Release_Date)
VALUES (4, 'v0.9.0-beta', DATE '2025-04-01');

INSERT INTO VERSION (Software_ID, Version_Number, Release_Date)
VALUES (5, 'v0.1.0', DATE '2025-06-01');

INSERT INTO VERSION (Software_ID, Version_Number, Release_Date)
VALUES (6, 'v1.0.0', DATE '2024-09-15');

-- 7. SAMPLE BUGS
INSERT INTO BUG
(Software_ID, Description, Severity, Status, Reported_Date)
VALUES
(1, 'Attendance percentage calculation rounds down prematurely for fractional classes.',
 'Medium', 'Resolved', DATE '2025-04-16');

INSERT INTO BUG
(Software_ID, Description, Severity, Status, Reported_Date)
VALUES
(1, 'Concurrent swipe submission causes duplicate attendance records during peak hours.',
 'High', 'Open', DATE '2025-05-02');

INSERT INTO BUG
(Software_ID, Description, Severity, Status, Reported_Date)
VALUES
(2, 'Payment webhook signature verification times out under high SSL payload.',
 'Critical', 'In Progress', DATE '2025-05-10');

INSERT INTO BUG
(Software_ID, Description, Severity, Status, Reported_Date)
VALUES
(2, 'Invoice PDF generation missing GST number in header summary.',
 'Low', 'Closed', DATE '2025-03-20');

INSERT INTO BUG
(Software_ID, Description, Severity, Status, Reported_Date)
VALUES
(3, 'Patient allergy badge not rendering in red on high contrast screens.',
 'Low', 'Resolved', DATE '2025-02-14');

INSERT INTO BUG
(Software_ID, Description, Severity, Status, Reported_Date)
VALUES
(3, 'Session cookie fails to invalidate immediately on remote doctor logout.',
 'High', 'Open', DATE '2025-04-28');

INSERT INTO BUG
(Software_ID, Description, Severity, Status, Reported_Date)
VALUES
(4, 'Memory leak observed in inference worker process after 10,000 requests.',
 'Critical', 'Open', DATE '2025-05-15');

INSERT INTO BUG
(Software_ID, Description, Severity, Status, Reported_Date)
VALUES
(5, 'Lockdown browser fails to intercept dual-monitor displays on macOS.',
 'High', 'In Progress', DATE '2025-06-10');

-- 8. SAMPLE MAINTENANCE
INSERT INTO MAINTENANCE
(Bug_ID, Maintenance_Date, Description, Performed_By, Status)
VALUES
(1, DATE '2025-04-18',
 'Adjusted floating point division to 2 decimal places using math.ceil rounding rule.',
 1, 'Completed');

INSERT INTO MAINTENANCE
(Bug_ID, Maintenance_Date, Description, Performed_By, Status)
VALUES
(3, DATE '2025-05-12',
 'Increased webhook timeout threshold to 15s and added retry queue via Celery.',
 3, 'In Progress');

INSERT INTO MAINTENANCE
(Bug_ID, Maintenance_Date, Description, Performed_By, Status)
VALUES
(4, DATE '2025-03-22',
 'Updated ReportLab template to include GSTIN variable in invoice header.',
 2, 'Completed');

INSERT INTO MAINTENANCE
(Bug_ID, Maintenance_Date, Description, Performed_By, Status)
VALUES
(5, DATE '2025-02-16',
 'Corrected CSS specificity rule and color contrast token for allergy badge.',
 4, 'Completed');

INSERT INTO MAINTENANCE
(Bug_ID, Maintenance_Date, Description, Performed_By, Status)
VALUES
(7, DATE '2025-05-18',
 'Profiled inference pipeline with memory-profiler; patch submitted for Tensor deallocation.',
 5, 'In Progress');

INSERT INTO MAINTENANCE
(Bug_ID, Maintenance_Date, Description, Performed_By, Status)
VALUES
(8, DATE '2025-06-12',
 'Invoked CoreGraphics display enumeration API to disable external virtual screens.',
 6, 'In Progress');

-- 9. SAMPLE LICENSES
INSERT INTO LICENSE
(Software_ID, License_Type, Start_Date, Expiry_Date, License_Status)
VALUES
(1, 'MIT License', DATE '2024-01-01', DATE '2028-12-31', 'Active');

INSERT INTO LICENSE
(Software_ID, License_Type, Start_Date, Expiry_Date, License_Status)
VALUES
(2, 'Commercial Proprietary', DATE '2024-06-01', DATE '2025-05-31', 'Expired');

INSERT INTO LICENSE
(Software_ID, License_Type, Start_Date, Expiry_Date, License_Status)
VALUES
(3, 'Enterprise Subscription', DATE '2024-03-15', DATE '2025-03-14', 'Expired');

INSERT INTO LICENSE
(Software_ID, License_Type, Start_Date, Expiry_Date, License_Status)
VALUES
(3, 'Enterprise Subscription (Renewed)', DATE '2025-03-15', DATE '2026-03-14', 'Active');

INSERT INTO LICENSE
(Software_ID, License_Type, Start_Date, Expiry_Date, License_Status)
VALUES
(4, 'Apache 2.0', DATE '2025-01-01', DATE '2029-12-31', 'Active');

INSERT INTO LICENSE
(Software_ID, License_Type, Start_Date, Expiry_Date, License_Status)
VALUES
(5, 'Educational Campus License', DATE '2025-01-01', DATE '2025-12-31', 'Active');

INSERT INTO LICENSE
(Software_ID, License_Type, Start_Date, Expiry_Date, License_Status)
VALUES
(6, 'GNU GPL v3', DATE '2023-01-01', DATE '2024-12-31', 'Expired');

-- 10. SAMPLE TECHNOLOGIES
INSERT INTO TECHNOLOGY
(Technology_Name, Technology_Type, Version, Description)
VALUES
('Python', 'Programming Language', '3.11',
 'High-level programming language known for readability and rich libraries.');

INSERT INTO TECHNOLOGY
(Technology_Name, Technology_Type, Version, Description)
VALUES
('Flask', 'Web Framework', '3.0.2',
 'Lightweight WSGI web application microframework for Python.');

INSERT INTO TECHNOLOGY
(Technology_Name, Technology_Type, Version, Description)
VALUES
('MySQL', 'Relational Database', '8.0',
 'Enterprise open-source relational database management system.');

INSERT INTO TECHNOLOGY
(Technology_Name, Technology_Type, Version, Description)
VALUES
('JavaScript', 'Frontend Language', 'ES2023',
 'Client-side dynamic scripting language for web browsers.');

INSERT INTO TECHNOLOGY
(Technology_Name, Technology_Type, Version, Description)
VALUES
('FastAPI', 'API Framework', '0.110',
 'Modern, fast web framework for building APIs with Python 3.8+.');

INSERT INTO TECHNOLOGY
(Technology_Name, Technology_Type, Version, Description)
VALUES
('React.js', 'Frontend Framework', '18.2',
 'Declarative, component-based user interface library.');

INSERT INTO TECHNOLOGY
(Technology_Name, Technology_Type, Version, Description)
VALUES
('Docker', 'DevOps / Container', '24.0',
 'Platform for developing, shipping, and running containerized applications.');

INSERT INTO TECHNOLOGY
(Technology_Name, Technology_Type, Version, Description)
VALUES
('Redis', 'In-Memory Cache', '7.2',
 'In-memory key-value data store used for caching and message queuing.');

-- 11. SAMPLE SOFTWARE_TECHNOLOGY
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (1, 1);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (1, 2);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (1, 3);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (1, 4);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (2, 1);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (2, 2);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (2, 3);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (2, 8);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (3, 3);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (3, 6);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (3, 7);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (4, 1);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (4, 5);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (4, 7);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (5, 4);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (6, 1);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (6, 3);

COMMIT;

-- ================================================================
-- STEP 4: DEMO / REPORT QUERIES
-- These are Oracle versions of the original MySQL report queries.
-- ================================================================

-- 1. Projects with departments
SELECT p.Project_ID, p.Project_Name, p.Project_Status,
       d.Department_Name, d.Location
FROM PROJECT p
INNER JOIN DEPARTMENT d ON p.Department_ID = d.Department_ID;

-- 2. Developers with departments
SELECT dev.Developer_ID, dev.Developer_Name, dev.Email,
       d.Department_Name
FROM DEVELOPER dev
INNER JOIN DEPARTMENT d ON dev.Department_ID = d.Department_ID;

-- 3. Software with projects
SELECT s.Software_ID, s.Software_Name, s.Status,
       p.Project_Name, p.Project_Status
FROM SOFTWARE s
INNER JOIN PROJECT p ON s.Project_ID = p.Project_ID;

-- 4. Software with versions
SELECT s.Software_Name, v.Version_Number, v.Release_Date
FROM SOFTWARE s
INNER JOIN VERSION v ON s.Software_ID = v.Software_ID
ORDER BY s.Software_Name, v.Release_Date DESC;

-- 5. Software with bugs
SELECT s.Software_Name, b.Bug_ID, b.Description,
       b.Severity, b.Status, b.Reported_Date
FROM SOFTWARE s
INNER JOIN BUG b ON s.Software_ID = b.Software_ID;

-- 6. Bugs grouped by severity
SELECT Severity, COUNT(Bug_ID) AS Total_Bugs
FROM BUG
GROUP BY Severity
ORDER BY Total_Bugs DESC;

-- 7. Bugs grouped by status
SELECT Status, COUNT(Bug_ID) AS Total_Bugs
FROM BUG
GROUP BY Status;

-- 8. Maintenance records with developer names
SELECT m.Maintenance_ID,
       b.Description AS Bug_Description,
       m.Maintenance_Date,
       dev.Developer_Name,
       m.Status AS Maintenance_Status
FROM MAINTENANCE m
INNER JOIN BUG b ON m.Bug_ID = b.Bug_ID
INNER JOIN DEVELOPER dev ON m.Performed_By = dev.Developer_ID;

-- 9. Software with licenses
SELECT s.Software_Name,
       l.License_Type,
       l.Start_Date,
       l.Expiry_Date,
       l.License_Status,
       CASE
           WHEN l.Expiry_Date < SYSDATE THEN 'EXPIRED'
           ELSE 'VALID'
       END AS Expiry_Check
FROM SOFTWARE s
INNER JOIN LICENSE l ON s.Software_ID = l.Software_ID;

-- 10. Software and technologies used
-- Oracle equivalent of MySQL GROUP_CONCAT
SELECT s.Software_Name,
       LISTAGG(t.Technology_Name, ', ')
           WITHIN GROUP (ORDER BY t.Technology_Name) AS Technologies_Used
FROM SOFTWARE s
INNER JOIN SOFTWARE_TECHNOLOGY st
    ON s.Software_ID = st.Software_ID
INNER JOIN TECHNOLOGY t
    ON st.Technology_ID = t.Technology_ID
GROUP BY s.Software_ID, s.Software_Name;

-- 11. Projects grouped by department
SELECT d.Department_Name,
       COUNT(p.Project_ID) AS Project_Count
FROM DEPARTMENT d
LEFT JOIN PROJECT p ON d.Department_ID = p.Department_ID
GROUP BY d.Department_ID, d.Department_Name;

-- 12. Developers grouped by department
SELECT d.Department_Name,
       COUNT(dev.Developer_ID) AS Developer_Count
FROM DEPARTMENT d
LEFT JOIN DEVELOPER dev
    ON d.Department_ID = dev.Department_ID
GROUP BY d.Department_ID, d.Department_Name;

-- 13. Expired licenses
SELECT l.License_ID,
       s.Software_Name,
       l.License_Type,
       l.Expiry_Date,
       TRUNC(SYSDATE) - TRUNC(l.Expiry_Date) AS Days_Expired
FROM LICENSE l
INNER JOIN SOFTWARE s ON l.Software_ID = s.Software_ID
WHERE l.Expiry_Date < SYSDATE;

-- 14. Open bugs
SELECT b.Bug_ID,
       s.Software_Name,
       b.Description,
       b.Severity,
       b.Reported_Date
FROM BUG b
INNER JOIN SOFTWARE s ON b.Software_ID = s.Software_ID
WHERE b.Status = 'Open';

-- 15. Software having at least one bug
SELECT s.Software_ID,
       s.Software_Name,
       COUNT(b.Bug_ID) AS Bug_Count
FROM SOFTWARE s
INNER JOIN BUG b ON s.Software_ID = b.Software_ID
GROUP BY s.Software_ID, s.Software_Name
HAVING COUNT(b.Bug_ID) >= 1
ORDER BY Bug_Count DESC;

-- ================================================================
-- END OF SOFTWARE MANAGEMENT SYSTEM DATABASE
-- ================================================================
