-- =====================================================================
-- DATABASE SCRIPT FOR ORACLE DATABASE (SQL*Plus)
-- SOFTWARE MANAGEMENT SYSTEM - College DBMS Project (2nd Year CSE)
-- Compatible with Oracle Database 23ai / 21c / 19c / 11g / Express Edition
-- =====================================================================

-- To run this script in SQL*Plus command line, type:
-- @C:\Users\subha\OneDrive\Desktop\software_management_system\oracle_database.sql

SET DEFINE OFF;
SET FEEDBACK ON;

-- Drop existing tables in reverse foreign-key dependency order
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SOFTWARE_TECHNOLOGY CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE MAINTENANCE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BUG CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE VERSION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE LICENSE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SOFTWARE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PROJECT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DEPARTMENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "USER" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TECHNOLOGY CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- =====================================================================
-- TABLE 1: "USER"
-- (USER is a reserved keyword in Oracle, so double quotes are used)
-- =====================================================================
CREATE TABLE "USER" (
    User_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) NOT NULL UNIQUE,
    Password VARCHAR2(255) NOT NULL
);

-- =====================================================================
-- TABLE 2: DEPARTMENT
-- =====================================================================
CREATE TABLE DEPARTMENT (
    Department_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Department_Name VARCHAR2(100) NOT NULL,
    Description CLOB,
    Location VARCHAR2(100),
    Contact_Email VARCHAR2(100)
);

-- =====================================================================
-- TABLE 3: PROJECT
-- Relationship: DEPARTMENT 1:N PROJECT (owns)
-- =====================================================================
CREATE TABLE PROJECT (
    Project_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Project_Name VARCHAR2(150) NOT NULL,
    Description CLOB,
    Start_Date DATE,
    End_Date DATE,
    Project_Status VARCHAR2(50) DEFAULT 'Planning',
    Department_ID NUMBER NOT NULL,
    CONSTRAINT fk_proj_dept FOREIGN KEY (Department_ID) REFERENCES DEPARTMENT(Department_ID) ON DELETE CASCADE
);

-- =====================================================================
-- TABLE 4: DEVELOPER
-- Relationship: DEPARTMENT 1:N DEVELOPER (employs)
-- =====================================================================
CREATE TABLE DEVELOPER (
    Developer_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Developer_Name VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) NOT NULL,
    Department_ID NUMBER NOT NULL,
    CONSTRAINT fk_dev_dept FOREIGN KEY (Department_ID) REFERENCES DEPARTMENT(Department_ID) ON DELETE CASCADE
);

-- =====================================================================
-- TABLE 5: SOFTWARE
-- Relationship: PROJECT 1:N SOFTWARE (contains)
-- =====================================================================
CREATE TABLE SOFTWARE (
    Software_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Software_Name VARCHAR2(150) NOT NULL,
    Description CLOB,
    Status VARCHAR2(50) DEFAULT 'Active',
    Project_ID NUMBER NOT NULL,
    CONSTRAINT fk_sw_proj FOREIGN KEY (Project_ID) REFERENCES PROJECT(Project_ID) ON DELETE CASCADE
);

-- =====================================================================
-- TABLE 6: VERSION
-- Relationship: SOFTWARE 1:N VERSION (has)
-- =====================================================================
CREATE TABLE VERSION (
    Version_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Software_ID NUMBER NOT NULL,
    Version_Number VARCHAR2(50) NOT NULL,
    Release_Date DATE NOT NULL,
    CONSTRAINT fk_ver_sw FOREIGN KEY (Software_ID) REFERENCES SOFTWARE(Software_ID) ON DELETE CASCADE
);

-- =====================================================================
-- TABLE 7: BUG
-- Relationship: SOFTWARE 1:N BUG (has)
-- =====================================================================
CREATE TABLE BUG (
    Bug_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Software_ID NUMBER NOT NULL,
    Description CLOB NOT NULL,
    Severity VARCHAR2(30) DEFAULT 'Medium' NOT NULL,
    Status VARCHAR2(30) DEFAULT 'Open' NOT NULL,
    Reported_Date DATE NOT NULL,
    CONSTRAINT fk_bug_sw FOREIGN KEY (Software_ID) REFERENCES SOFTWARE(Software_ID) ON DELETE CASCADE
);

-- =====================================================================
-- TABLE 8: MAINTENANCE
-- Relationships: BUG 1:N MAINTENANCE (fixed_by)
--                DEVELOPER 1:N MAINTENANCE (performs)
-- =====================================================================
CREATE TABLE MAINTENANCE (
    Maintenance_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Bug_ID NUMBER NOT NULL,
    Maintenance_Date DATE NOT NULL,
    Description CLOB NOT NULL,
    Performed_By NUMBER NOT NULL,
    Status VARCHAR2(30) DEFAULT 'In Progress' NOT NULL,
    CONSTRAINT fk_maint_bug FOREIGN KEY (Bug_ID) REFERENCES BUG(Bug_ID) ON DELETE CASCADE,
    CONSTRAINT fk_maint_dev FOREIGN KEY (Performed_By) REFERENCES DEVELOPER(Developer_ID) ON DELETE CASCADE
);

-- =====================================================================
-- TABLE 9: LICENSE
-- Relationship: SOFTWARE 1:N LICENSE (covered_by)
-- =====================================================================
CREATE TABLE LICENSE (
    License_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Software_ID NUMBER NOT NULL,
    License_Type VARCHAR2(50) NOT NULL,
    Start_Date DATE NOT NULL,
    Expiry_Date DATE NOT NULL,
    License_Status VARCHAR2(30) DEFAULT 'Active' NOT NULL,
    CONSTRAINT fk_lic_sw FOREIGN KEY (Software_ID) REFERENCES SOFTWARE(Software_ID) ON DELETE CASCADE
);

-- =====================================================================
-- TABLE 10: TECHNOLOGY
-- =====================================================================
CREATE TABLE TECHNOLOGY (
    Technology_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Technology_Name VARCHAR2(100) NOT NULL,
    Technology_Type VARCHAR2(50) NOT NULL,
    Version VARCHAR2(50),
    Description CLOB
);

-- =====================================================================
-- TABLE 11: SOFTWARE_TECHNOLOGY (Junction Table M:N)
-- Relationships: SOFTWARE 1:N SOFTWARE_TECHNOLOGY (uses)
--                TECHNOLOGY 1:N SOFTWARE_TECHNOLOGY (used_in)
-- =====================================================================
CREATE TABLE SOFTWARE_TECHNOLOGY (
    Software_ID NUMBER NOT NULL,
    Technology_ID NUMBER NOT NULL,
    PRIMARY KEY (Software_ID, Technology_ID),
    CONSTRAINT fk_st_sw FOREIGN KEY (Software_ID) REFERENCES SOFTWARE(Software_ID) ON DELETE CASCADE,
    CONSTRAINT fk_st_tech FOREIGN KEY (Technology_ID) REFERENCES TECHNOLOGY(Technology_ID) ON DELETE CASCADE
);

-- =====================================================================
-- SAMPLE DATA INSERTION (Oracle SQL Syntax)
-- =====================================================================

-- 1. Insert Users
INSERT INTO "USER" (Name, Email, Password) VALUES ('System Administrator', 'admin@sms.com', 'scrypt:32768:8:1$jEYU4vilnsMMruON$a8696cbd3566358aa712ad7ec8f6de05dbeff5011208ca5470f645a75466acb928d29720b64e2c0708347957b3ab4a7d173178c4e74b4912342e7b3603bb7386');
INSERT INTO "USER" (Name, Email, Password) VALUES ('Prof. Rajesh Sharma', 'rajesh.sharma@sms.com', 'scrypt:32768:8:1$jEYU4vilnsMMruON$a8696cbd3566358aa712ad7ec8f6de05dbeff5011208ca5470f645a75466acb928d29720b64e2c0708347957b3ab4a7d173178c4e74b4912342e7b3603bb7386');

-- 2. Insert Departments
INSERT INTO DEPARTMENT (Department_Name, Description, Location, Contact_Email) VALUES ('Computer Science and Engineering', 'Core computing and systems engineering.', 'Building 3, Floor 2', 'cse.dept@college.edu');
INSERT INTO DEPARTMENT (Department_Name, Description, Location, Contact_Email) VALUES ('Information Technology', 'Enterprise information systems and cloud.', 'Building 2, Floor 1', 'it.dept@college.edu');
INSERT INTO DEPARTMENT (Department_Name, Description, Location, Contact_Email) VALUES ('Data Science and AI', 'Machine learning and predictive modeling.', 'Academic Block A, Floor 4', 'ai.dept@college.edu');
INSERT INTO DEPARTMENT (Department_Name, Description, Location, Contact_Email) VALUES ('Software Quality Assurance', 'Testing, security auditing, and reliability.', 'Innovation Center, Room 102', 'qa.dept@college.edu');

-- 3. Insert Projects
INSERT INTO PROJECT (Project_Name, Description, Start_Date, End_Date, Project_Status, Department_ID) VALUES ('Campus ERP Platform', 'Integrated portal for attendance and grading.', DATE '2025-01-10', DATE '2025-12-20', 'In Progress', 1);
INSERT INTO PROJECT (Project_Name, Description, Start_Date, End_Date, Project_Status, Department_ID) VALUES ('Healthcare Management Suite', 'Clinical workflow system for hospital records.', DATE '2024-06-01', DATE '2025-05-30', 'Completed', 2);
INSERT INTO PROJECT (Project_Name, Description, Start_Date, End_Date, Project_Status, Department_ID) VALUES ('Predictive Analytics Engine', 'AI-powered student performance predictor.', DATE '2025-03-01', DATE '2026-02-28', 'In Progress', 3);
INSERT INTO PROJECT (Project_Name, Description, Start_Date, End_Date, Project_Status, Department_ID) VALUES ('Secure Exam Portal', 'Proctored online examination software.', DATE '2025-02-15', DATE '2025-11-30', 'Planning', 4);

-- 4. Insert Developers
INSERT INTO DEVELOPER (Developer_Name, Email, Department_ID) VALUES ('Rahul Verma', 'rahul.verma@college.edu', 1);
INSERT INTO DEVELOPER (Developer_Name, Email, Department_ID) VALUES ('Priya Nair', 'priya.nair@college.edu', 1);
INSERT INTO DEVELOPER (Developer_Name, Email, Department_ID) VALUES ('Arjun Mehta', 'arjun.mehta@college.edu', 2);
INSERT INTO DEVELOPER (Developer_Name, Email, Department_ID) VALUES ('Sneha Roy', 'sneha.roy@college.edu', 2);
INSERT INTO DEVELOPER (Developer_Name, Email, Department_ID) VALUES ('Vikram Patel', 'vikram.patel@college.edu', 3);

-- 5. Insert Software
INSERT INTO SOFTWARE (Software_Name, Description, Status, Project_ID) VALUES ('Student Attendance Tracker', 'Biometric attendance web application.', 'Active', 1);
INSERT INTO SOFTWARE (Software_Name, Description, Status, Project_ID) VALUES ('Fee Payment Gateway Service', 'Online tuition fee transactions.', 'Active', 1);
INSERT INTO SOFTWARE (Software_Name, Description, Status, Project_ID) VALUES ('Electronic Medical Record App', 'Patient chart and diagnostic summary.', 'Active', 2);
INSERT INTO SOFTWARE (Software_Name, Description, Status, Project_ID) VALUES ('ML Model Serving API', 'FastAPI microservice for ML predictions.', 'Active', 3);

-- 6. Insert Versions
INSERT INTO VERSION (Software_ID, Version_Number, Release_Date) VALUES (1, 'v1.0.0', DATE '2025-02-01');
INSERT INTO VERSION (Software_ID, Version_Number, Release_Date) VALUES (1, 'v1.1.0', DATE '2025-04-15');
INSERT INTO VERSION (Software_ID, Version_Number, Release_Date) VALUES (2, 'v1.0.0', DATE '2025-03-01');
INSERT INTO VERSION (Software_ID, Version_Number, Release_Date) VALUES (3, 'v3.2.0', DATE '2024-11-20');

-- 7. Insert Bugs
INSERT INTO BUG (Software_ID, Description, Severity, Status, Reported_Date) VALUES (1, 'Attendance percentage calculation rounds down prematurely.', 'Medium', 'Resolved', DATE '2025-04-16');
INSERT INTO BUG (Software_ID, Description, Severity, Status, Reported_Date) VALUES (1, 'Concurrent swipe submission causes duplicate records.', 'High', 'Open', DATE '2025-05-02');
INSERT INTO BUG (Software_ID, Description, Severity, Status, Reported_Date) VALUES (2, 'Payment webhook signature verification timeout.', 'Critical', 'In Progress', DATE '2025-05-10');
INSERT INTO BUG (Software_ID, Description, Severity, Status, Reported_Date) VALUES (3, 'Session cookie fails to invalidate on doctor logout.', 'High', 'Open', DATE '2025-04-28');

-- 8. Insert Maintenance
INSERT INTO MAINTENANCE (Bug_ID, Maintenance_Date, Description, Performed_By, Status) VALUES (1, DATE '2025-04-18', 'Adjusted floating point division to 2 decimal places.', 1, 'Completed');
INSERT INTO MAINTENANCE (Bug_ID, Maintenance_Date, Description, Performed_By, Status) VALUES (3, DATE '2025-05-12', 'Increased webhook timeout threshold to 15s.', 3, 'In Progress');

-- 9. Insert Licenses
INSERT INTO LICENSE (Software_ID, License_Type, Start_Date, Expiry_Date, License_Status) VALUES (1, 'MIT License', DATE '2024-01-01', DATE '2028-12-31', 'Active');
INSERT INTO LICENSE (Software_ID, License_Type, Start_Date, Expiry_Date, License_Status) VALUES (2, 'Commercial Proprietary', DATE '2024-06-01', DATE '2025-05-31', 'Expired');
INSERT INTO LICENSE (Software_ID, License_Type, Start_Date, Expiry_Date, License_Status) VALUES (3, 'Enterprise Subscription', DATE '2024-03-15', DATE '2025-03-14', 'Expired');
INSERT INTO LICENSE (Software_ID, License_Type, Start_Date, Expiry_Date, License_Status) VALUES (4, 'Apache 2.0', DATE '2025-01-01', DATE '2029-12-31', 'Active');

-- 10. Insert Technologies
INSERT INTO TECHNOLOGY (Technology_Name, Technology_Type, Version, Description) VALUES ('Python', 'Programming Language', '3.11', 'High-level programming language.');
INSERT INTO TECHNOLOGY (Technology_Name, Technology_Type, Version, Description) VALUES ('Flask', 'Web Framework', '3.0.2', 'Lightweight WSGI web microframework.');
INSERT INTO TECHNOLOGY (Technology_Name, Technology_Type, Version, Description) VALUES ('Oracle / MySQL', 'Relational Database', 'Enterprise', 'Relational database management system.');
INSERT INTO TECHNOLOGY (Technology_Name, Technology_Type, Version, Description) VALUES ('JavaScript', 'Frontend Language', 'ES2023', 'Client-side dynamic scripting language.');

-- 11. Insert Software_Technology (M:N)
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (1, 1);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (1, 2);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (1, 3);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (1, 4);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (2, 1);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (2, 2);
INSERT INTO SOFTWARE_TECHNOLOGY (Software_ID, Technology_ID) VALUES (3, 3);

COMMIT;
